//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileLog
    {
        public int Id { get; set; }
        public string Filename { get; set; }
        public string Filepath { get; set; }
        public Nullable<int> Filetype { get; set; }
        public Nullable<int> TotalRecords { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
