//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostvetResult
    {
        public int Id { get; set; }
        public Nullable<int> FileId { get; set; }
        public string IDN { get; set; }
        public string Outcome { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
