//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivationResult
    {
        public int Id { get; set; }
        public int FileId { get; set; }
        public string MSISDN { get; set; }
        public string Outcome { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
