//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string RegistrationNo { get; set; }
        public string CKDocsRecieved { get; set; }
        public string Director1Name { get; set; }
        public string Director1RSAID { get; set; }
        public string Director1ContactNo { get; set; }
        public string Director2Name { get; set; }
        public string Director2RSAID { get; set; }
        public string Director2ContactNo { get; set; }
        public string PhysicalAddress1 { get; set; }
        public string PhysicalSuburb { get; set; }
        public string PhysicalTown { get; set; }
        public string PhysicalProvince { get; set; }
        public string PhysicalPostCode { get; set; }
        public string PostalAddress1 { get; set; }
        public string PostalSuburb { get; set; }
        public string PostalTown { get; set; }
        public string PostalProvince { get; set; }
        public string PostalPostCode { get; set; }
        public string PrimaryContactName { get; set; }
        public string PrimaryContactTel { get; set; }
    }
}
