//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public int CustomerType { get; set; }
        public int CompanyId { get; set; }
        public string RSAID { get; set; }
        public string Title { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string TelMobileNo { get; set; }
        public string TelMobile2No { get; set; }
        public string TelHomeNo { get; set; }
        public string TelWorkNo { get; set; }
        public string Email { get; set; }
        public string DeliveryAddress1 { get; set; }
        public string DeliveryStreet { get; set; }
        public string DeliverySuburb { get; set; }
        public string DeliveryProvince { get; set; }
        public string DeliveryTown { get; set; }
        public string DeliveryPostCode { get; set; }
        public string DeliveryNotes { get; set; }
        public string DeliveryContactNo { get; set; }
        public string DeliveryGPS { get; set; }
        public string DeliveryLandmark { get; set; }
    }
}
