//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public int Id { get; set; }
        public int DatasetId { get; set; }
        public string RSAID { get; set; }
        public string Title { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string TelMobile1 { get; set; }
        public string TelMobile2 { get; set; }
        public string TelMobile3 { get; set; }
        public string TelMobile4 { get; set; }
        public string TelHome { get; set; }
        public string TelWork { get; set; }
        public string CreditScore { get; set; }
        public string CompanyName { get; set; }
    }
}
