//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reason
    {
        public int Id { get; set; }
        public Nullable<int> WorkQueueId { get; set; }
        public string ReasonType { get; set; }
        public string Description { get; set; }
    }
}
