//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TeamleaderId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> LOBId { get; set; }
    }
}
